#!/bin/sh
cd build
#meson ..

# Check the exit status
if [ $? -ne 0 ]; then
    echo "Error: Command failed with exit code $?"
    exit 1
fi

ninja

# Check the exit status
if [ $? -ne 0 ]; then
    echo "Error: Command failed with exit code $?"
    exit 1
fi

./src/teapot